apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoui-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoui-api
  template:
    metadata:
      labels:
        app: todoui-api
    spec:
      containers:
      - name: todoui-api
        image: acrdevtodoproject010.azurecr.io/micro-todo-ui-api:v1
        ports:
        - containerPort: 80
