apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-ui
  template:
    metadata:
      labels:
        app: todo-ui
    spec:
      containers:
      - name: todo-ui
        image: acrdevtodoproject010.azurecr.io/micro-todo-ui-api:v1
        ports:
        - containerPort: 80
