apiVersion:  networking.k8s.io/v1
kind:  Ingress
metadata:
  name:  ingress-todoui
  labels:
    app:  todoui
spec:  
  ingressClassName:  azure-application-gateway
  rules:
  - host: todoui.techno028.shop
    http:
     paths:
     - path: "/"
       pathType:  Prefix
       backend:
         service:
           name: todoui-api
           port: 
            number:  80

