apiVersion:  networking.k8s.io/v1
kind:  Ingress
metadata:
  name:  ingress-addtasks 
  labels:
    app:  addtasks
spec:  
  ingressClassName:  azure-application-gateway
  rules:
  - host: addtask.techno028.shop
    http:
     paths:
     - path: "/"
       pathType:  Prefix
       backend:
         service:
           name:  todo-add-tasks-api
           port: 
            number:  80

